version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker_volumes/jenkins:/var/jenkins_home
